### ISSUE TITLE
Storybook isn't working due to a scss import

### ISSUE THREAD

**Issue by bernabe9** [yankaindustries/mc-components#1]
Error: 
```
Module build failed: 
@import "./lib/lib";
^
      File to import not found or unreadable: ./lib/lib.
```

<img width="1233" alt="screen shot 2018-06-13 at 8 38 22 pm" src="https://user-images.githubusercontent.com/18464392/41384000-e3681dbc-6f49-11e8-86f9-3a2bdcfba332.png">

**Comment by stephenp** [comment]
Fixed with https://github.com/yankaindustries/mc-components/pull/2
