### ISSUE TITLE
CloseIcon does not need to be a component

### ISSUE THREAD

**Issue by jstnjns** [yankaindustries/mc-components#109]
The close icon has a color and click handler.

I assume the color is a prop so that it can be changed either by some action/state change, or based on circumstance.  This can be done with CSS.

A click handler is no necessary if we simply wrap the icon in an anchor tag and set an `onClick` prop there.

**Comment by jstnjns** [comment]
Somewhat changing this, but will be removing the manually created React components.  Opting to have components automatically generated using [svgr](https://github.com/smooth-code/svgr)

**Comment by stephenp** [comment]
Icons updated with #141
