### ISSUE TITLE
Image Tile Component.

### ISSUE THREAD

**Issue by jesseocon** [yankaindustries/mc-components#11]
UserStory: 
As a developer when I create an image tile I should have a component that automates the process.

The component should allow me to:
* pass in the url of an image
* select the aspect ratio - 16x9 or 4x3
* accept children
* accept click handlers
* accept hover handlers
* allow children to be absolutely positioned. 
* have a loading state to transition between hover and selected when the check appears. This is to handle the asynchronous nature of an http call. I don't want to immediately check the box because if the call fails then it will be confusing.

The component should have no opinion on its overall size. It should fill to the width of its container. 

Up for discussion - 
* how is the check behavior implemented. 
* How are different icons handled?
* Are there different components for each variation?

### Check Tile - checked state
![image](https://user-images.githubusercontent.com/1948630/41450210-f52fc0aa-701a-11e8-984a-babf82cdec9f.png)

### Check Tile - no hover, no check 
![image](https://user-images.githubusercontent.com/1948630/41450258-4e4ae0de-701b-11e8-922e-cde36f05e9d8.png)

### Check Tile - hover state, no check
![image](https://user-images.githubusercontent.com/1948630/41450272-6e88d96e-701b-11e8-9145-d3e14fb468fe.png)

### Coming Soon Tile - hover state
![image](https://user-images.githubusercontent.com/1948630/41450384-1e425c72-701c-11e8-9d9f-b9d51a22f93a.png)

### Coming Soon Tile - no hover
![image](https://user-images.githubusercontent.com/1948630/41450395-36e3527c-701c-11e8-8289-0443390d6bdd.png)

### Play Tile - no hover
![image](https://user-images.githubusercontent.com/1948630/41450406-548d8e1e-701c-11e8-9c56-83a6fcc76d84.png)

### Check Tile from End Card
![image](https://user-images.githubusercontent.com/1948630/41450544-5743aa48-701d-11e8-8229-e3a79e8dee38.png)

**Comment by jstnjns** [comment]
Here I see multiple components, not just `ImageTile` with the ability to add a checkbox.  I will create another issue for `CheckTile` which shall utilize a generic `ImageTile`

**Comment by jstnjns** [comment]
Ah, jk.  It looks like this component is already built out.  However, it doesn't coincide with the general philosophy about how to build components like this.  I'll close this ticket, and then add some tickets for things that need to be addressed about the implementation.
