### ISSUE TITLE
Add Chapter Video Tile Component

### ISSUE THREAD

**Issue by jesseocon** [yankaindustries/mc-components#13]
## Description:
The chapter video displays the thumbnail of the chapter video and after .5s of hover is scales and starts playing the video. The video has sound and no controls. clicking on the video goes to the the chapter of the video playing.

### Requirements
* Should take a thumbnail image
* Should take a link address (for linking to the chapter)
* Should take a video hash
* Should take a video vendor type: (wistia, brightcove)

### Open questions
* Should the scaling be included in the component or should that be a something added via render props. I think it is currently the latter.

### Design file
https://www.figma.com/file/KQr5QmLmvKzpOaxp8oEBoXE6/Logged-In-HP

### Current implementation
The current implementation can be seen by: 
1. Clone: https://github.com/bernabe9/mc-assignment
2. If you don't have access slack Bernabé
3. yarn start
4. Hover any tile in **my classes**.

![2018-06-17 07 58 17](https://user-images.githubusercontent.com/1948630/41509143-5478f622-7204-11e8-8c17-eb224655f40e.gif)

**Comment by jstnjns** [comment]
This is now possible with Tile, TileImage, TileCaption, HoverHandler, and AnimationHandler.  See Storybook for details
