### ISSUE TITLE
Add Trailer Video Tile Component

### ISSUE THREAD

**Issue by jesseocon** [yankaindustries/mc-components#14]
## Description
In the explore classes area of the logged in homepage when the user hovers over a tile for .5second the video tile scales, a button becomes visible and the trailer video starts to play. 

### Requirements
* Should take a thumb url for the poster image
* Should take a link address for where the tile should link
* Should take a callback for click handler

### Current implementation
The current implementation can be seen by: 
1. Clone: https://github.com/bernabe9/mc-assignment
2. If you don't have access slack Bernabé
3. yarn start
4. Hover any tile in **explore classes**.
![2018-06-17 08 10 27](https://user-images.githubusercontent.com/1948630/41509310-a514e134-7206-11e8-94ee-e8e369f27f5c.gif)

**Comment by jstnjns** [comment]
This is solved with new `Tile` implementation
