### ISSUE TITLE
SCSS copied to lib folder?

### ISSUE THREAD

**Issue by stephenp** [yankaindustries/mc-components#15]
@a-axton and I were wondering...why does the scss get copied from src to lib?

**Comment by bernabe9** [comment]
When you publish a library through NPM is a good practice to ignore `src` folder to reduce the module size. Actually this file https://github.com/yankaindustries/mc-components/blob/develop/.npmignore is ignoring the `src` folder.

`lib` or `dist` usually represent the "public" folder

**Comment by stephenp** [comment]
Thoughts on moving all the `lib` contents to `dist`, and then having a `scss` and `css` folder within `styles`? So then anyone can consume the `dist` folder and reference both the sass variables and compiled css if they want it?

**Comment by stephenp** [comment]
https://github.com/yankaindustries/mc-components/pull/18
