### ISSUE TITLE
How should we support static html in storybook?

### ISSUE THREAD

**Issue by stephenp** [yankaindustries/mc-components#16]
Should we make separate stories for the react components vs static components?

**Comment by bernabe9** [comment]
Good question.
I think it would be confusing to have static components mixed in with react component. 
But we can set up another storybook in this repository.

Also, Im not sure if supporting static html structures should the scope of library 🤔 

Any thoughts? @a-axton @jesseocon

**Comment by a-axton** [comment]
We could have two root sections for static/react using this https://storybook.js.org/basics/writing-stories/#nesting-stories

**Comment by jstnjns** [comment]
@a-axton I think that's right on the money.  There will be a lot of things that are simply foundational to build apps that aren't necessarily React components, but still need to be in here (grid, typography, CSS util classes).

**Comment by jstnjns** [comment]
I did a little bit of digging, and to add some more structure to the navigation (and better segment non-React UI from the actual components) I think it'd be a good idea to make use of the `hierarchyRootSeparator` (https://github.com/storybooks/storybook/pull/2452).

My proposal for initial high level sections:

- Foundation (CSS)
  - Typography
  - Grid
- Components (React)
  - Forms
  - Media
  - Global

**Comment by bernabe9** [comment]
@jstnjns I love it. This way we can keep only one storybook and differentiate between non-react and React components using two high levels

**Comment by bernabe9** [comment]
It would be good to create a new folder inside the `src` to include there all the stories for the foundation (CSS).

**Comment by stephenp** [comment]
Fixed with #53 - if we want additional features (like actual subfolders in addition to UI subfolders), we should re-create this issue.
