### ISSUE TITLE
Modal updates

### ISSUE THREAD

**Issue by bernabe9** [yankaindustries/mc-components#165]
### Change modal's classname to prevent collisions
Currently we are using the classname `modal`. In MasterClass we are already using the classnames: `modal` and `mc-modal`

### Custom mount element
The default element is `modal-root`.

### Automatically create the mount element if it doesn't exist
Currently it's necessary to include the mount element in the html structure, otherwise the modal portal will fail.

**Comment by jstnjns** [comment]
Appears to have been done
