### ISSUE TITLE
ES Lint rules

### ISSUE THREAD

**Issue by stephenp** [yankaindustries/mc-components#17]
Need eslint rules for writing components

**Comment by bernabe9** [comment]
This project is already set up with eslint

**Comment by stephenp** [comment]
Sorry this wasn't clearer - this was something we brought up during our last meeting to look into further customizing the rules / sharing across different repos.

**Comment by bernabe9** [comment]
This could be useful https://github.com/Netflix/eslint-config-netflix

Looks easy to set up a repository with our rules and publish it via NPM
