### ISSUE TITLE
Rework tile inset as property

### ISSUE THREAD

**Issue by stephenp** [yankaindustries/mc-components#195]
The inset box shadow on tiles needs a little reworking - while it looks great on our class tiles, when you add a progress bar at the bottom, it's encompassing that too.  The inset border should only be on the image, or only on tiles without progress (up for discussion).

Tile with inset `box-shadow` (1px "white" border)
![image](https://user-images.githubusercontent.com/505670/44935181-8bc26180-ad24-11e8-8d76-760bc20d027d.png)

Tile with progress:
![image](https://user-images.githubusercontent.com/505670/44935197-9a107d80-ad24-11e8-9a09-03924225cc6c.png)

**Comment by jstnjns** [comment]
I propose it just goes on the image.  Not a fan of adding props for this sorta thing.
