### ISSUE TITLE
Form - Checkbox

### ISSUE THREAD

**Issue by stephenp** [yankaindustries/mc-components#197]
Looks like a checkbox component has been implemented in the main masterclass repo, and is already being overridden for experiments / different views.

The component is [here](https://github.com/yankaindustries/masterclass/blob/develop/app/javascript/components/FooterEmailForm/index.js
).

An example of an override being written is [here](https://github.com/yankaindustries/masterclass/pull/6859/files#diff-34e1206454280c5d1aeacea6c22b7585R8).

Let's get a component built out for checkboxes so that we can abstract this.

**Comment by stephenp** [comment]
Branch with styles here: https://github.com/yankaindustries/mc-components/tree/form-checkbox

**Comment by jstnjns** [comment]
#221
