### ISSUE TITLE
Sticky component

### ISSUE THREAD

**Issue by stephenp** [yankaindustries/mc-components#207]
Sticky nav, sticky header, sticky banner, etc.

- Offset from top
- Sticky from beginning, or sticky at scroll offset?

**Comment by jstnjns** [comment]
Possible implementation: https://github.com/jstnjns/masterclass/blob/react-homepage/app/javascript/components/Fixed/index.js

**Comment by jstnjns** [comment]
Actually, to keep this simple, let's just keep the props to: `position: ['top', 'bottom']`

**Comment by bcfancher-mc** [comment]
both of the above components have been added to satiate these requirements
