### ISSUE TITLE
Update typography styles

### ISSUE THREAD

**Issue by a-axton** [yankaindustries/mc-components#225]
The typography styles don't seem to match the ones being used from https://www.figma.com/file/X4sR3879DmwTYCRG72WKquAP/Master-Components?node-id=3929%3A1640

**Comment by stephenp** [comment]
That comp has changed a bit, the type styles we ended up going with use `mc-text-d1` through `d3` for the display styles, then standard "normal" looking `mc-text-h1` through `h5`.  Then you can pair those with the modifiers like `mc-text--bold` or `mc-text--uppercase`.

We were seeing designs that used "regular" headings vs the all caps so we wanted to make sure we could support all type styles.  Once design has them truly finalized, we can revisit the type styles in mc-components.

**Comment by a-axton** [comment]
@stephenp  I'm just seeing that some of the values in Master Components are different than mc-components. For example, h1 is 32px in mc-components but 24px in figma. We also don't have "paragraph 1, paragraph 2" in mc-components
