### ISSUE TITLE
Pull `Header` and `Footer` out of mc-components, move to masterclass shared

### ISSUE THREAD

**Issue by jstnjns** [yankaindustries/mc-components#229]
These are not components that make sense in a publicly shared library, they make more sense in the scope of the masterclass project.  This also makes it easier to perform experiments.

**Comment by stephenp** [comment]
Only pulled out header, still need to remove footer.

**Comment by stephenp** [comment]
Still have to remove these:

https://github.com/yankaindustries/mc-components/blob/develop/src/styles/components/_navbar-menu.scss

https://github.com/yankaindustries/mc-components/blob/develop/src/styles/release-candidate/components/_header.scss

**Comment by stephenp** [comment]
Removed all the things
