### ISSUE TITLE
some browsers don't support inline-flex on buttons

### ISSUE THREAD

**Issue by a-axton** [yankaindustries/mc-components#243]
Some browsers aren't centering button text properly (first observed on ipad simulator ios 10). More info here: https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers

![image](https://user-images.githubusercontent.com/4015654/46837286-93d0e080-cd69-11e8-9601-a839396e890d.png)

I ran into this issue on mc-fe-styles and opted to make another wrapper for icon buttons, we might be able to do something similar https://github.com/yankaindustries/mc-fe-styles/pull/37/files

**Comment by stephenp** [comment]
Thoughts on leaving it as `a` elements vs `button`?  I guess we should probably support either use case in CSS, but if it's in a component, then devs won't need to really worry about it.

**Comment by a-axton** [comment]
If we set them all as a tags then it isn't semantically correct. Like you said, if it's just a component then adding an extra wrapper for icon buttons won't really be noticed. So far I haven't even seen icon buttons used anywhere

**Comment by jstnjns** [comment]
In the cases that we use buttons as a submit, we need them to be `<button>`.  Is there a reason to have them as `inline-flex`?  Can we simply just use `inline-block`?

**Comment by a-axton** [comment]
We use inline-flex for the buttons with icons

**Comment by bcfancher-mc** [comment]
so far it seems like this is no longer the case for firefox.  I'm awaiting to hear from Win whether I can borrow an ipad to test on.  Will close if this is no longer the case on all these browsers

**Comment by bcfancher-mc** [comment]
I've tested on ipad as well.  Seems this is no longer an issue.  Closing.

**Comment by stephenp** [comment]
Encountering a different issue related to `inline-flex`...try adding the text "Download PDF" to a button with an icon on our demo storybook page and the text will wrap to two lines:

![image](https://user-images.githubusercontent.com/505670/75582931-7ca79700-5a21-11ea-9a5b-4c82fd09aa38.png)

Weirdly, adding more characters makes it stick to one line:

![image](https://user-images.githubusercontent.com/505670/75582950-8630ff00-5a21-11ea-837e-4519e6e6292a.png)

**Comment by stephenp** [comment]
The text wrapping was an issue with the parent wrapper overflow, not the button itself. This looks to be resolved.
