### ISSUE TITLE
Alternate footer component

### ISSUE THREAD

**Issue by stephenp** [yankaindustries/mc-components#25]
There are currently two types of footers.  The footer that is visible at [masterclass.com](http://masterclass.com) and [the cm page](https://www.masterclass.com/classes/gordon-ramsay-teaches-cooking).

The first is a traditional "footer", and the one on the course marketing (CM) pages is more social-based.  I'm not sure if this is something we'll want to continue supporting, or if it should be built as an "alternate" footer or a separate component completely.  Thoughts?

**Comment by a-axton** [comment]
I think we just just have one that is meant to be used in the "SPA" or behind the paywall app

**Comment by a-axton** [comment]
closing this for now, I think we decided to only have one variation
