### ISSUE TITLE
Set `line-height` prop for the Input component

### ISSUE THREAD

**Issue by bernabe9** [yankaindustries/mc-components#264]
The Input's heights depend on the `line-height` and we are not setting this value. Currently, the context(`line-height: inherit`) sets the height.

The class that doesn't set the line-height is `.mc-form-input__input`

**Comment by stephenp** [comment]
Is this still valid with the latest form updates @bernabe9 ? Or is this no longer an issue?

**Comment by stephenp** [comment]
I believe this is resolved
