### ISSUE TITLE
TextArea inconsistent text color & padding

### ISSUE THREAD

**Issue by bernabe9** [yankaindustries/mc-components#290]
The text area doesn't have the same text color as the input. Also, the padding is different.

Screenshot

![screen shot 2018-11-12 at 11 34 29 am](https://user-images.githubusercontent.com/18464392/48353871-2d442880-e66f-11e8-8ce4-70c12f32990f.png)

**Comment by stephenp** [comment]
Will be fixed when this PR is merged in: https://github.com/yankaindustries/mc-components/pull/282
