### ISSUE TITLE
Odd padding and font-size transition when component mounts

### ISSUE THREAD

**Issue by bernabe9** [yankaindustries/mc-components#291]
The input height & font size growth after it mounts.

**Expected behavior:** mount the input without any transition

Bug screenshot:

![transition-odd](https://user-images.githubusercontent.com/18464392/48354249-f7ec0a80-e66f-11e8-8386-39e4268c029f.gif)

**Comment by jstnjns** [comment]
Is this an issue with `mc-components`, or how styles are applied after the component mounts (being an issue for `masterclass`)?

**Comment by jstnjns** [comment]
i believe this to be the latter.  if you find that i am incorrect, reopen the issue and we can dig deeper
