### ISSUE TITLE
Rename button color variables

### ISSUE THREAD

**Issue by jstnjns** [yankaindustries/mc-components#302]
We should make the variable names explicit for button colors.  There was an issue relating to the tertiary button background being changed to transparent and the variable being used for text.  We could mitigate this if the use case for that variable was explicit and obvious (rendering the text usage invalid).

**Comment by stephenp** [comment]
Should rename / sync up our variable colors with what's shown in the figma comp:

https://www.figma.com/file/C9oEJgSdh4DnnIf2F6jJNqgd/Master-Components---Source-of-Truth---Version-0.8.5?node-id=267%3A65

I'm not sure when they got out of sync, but they're out of sync now (no secondary or tertiary colors at all)
