### ISSUE TITLE
custom scrollbar component

### ISSUE THREAD

**Issue by a-axton** [yankaindustries/mc-components#326]
I created a Scrollable component for the search bar and have seen it used in the new gifting flow as well. There are a few other places I think we could use it like the lesson subnav in chapters watch page. We would probably need a dark/light version. The styles are slightly different but maybe we could work with the design team to come up with unified styles.

![image](https://user-images.githubusercontent.com/4015654/50255280-1eefd780-03a6-11e9-95cb-d13bb0a246cf.png)
![image](https://user-images.githubusercontent.com/4015654/50255299-3202a780-03a6-11e9-8d35-8f664db4251d.png)

**Comment by stephenp** [comment]
Looks good to me - if design is on board with this I don't see a problem with updating the core style to be something like this instead of the default.  Do you know if this is styled on PC browsers the same? (I'm not sure what the latest is on which IE versions we need to support).

**Comment by a-axton** [comment]
I believe it looks the same. The scrollbars are really just divs and it hides the actual scrollbar with negative margins. There's some weird stuff with safari but I think I got it figured out

**Comment by jstnjns** [comment]
i'm for it.  maybe link to the implementation?  or if you wanna submit a PR that works too

**Comment by bcfancher-masterclass** [comment]
@a-axton did you ever get this in front of the design folks?

**Comment by a-axton** [comment]
I didn't, so far we haven't used this pattern very much. It might be worth bringing up in the weekly design meeting though

**Comment by bcfancher-mc** [comment]
let's go ahead and productize this
