### ISSUE TITLE
set text-align left for floating labels

### ISSUE THREAD

**Issue by a-axton** [yankaindustries/mc-components#336]
If there is a parent element with text align center then the floating labels are inheriting it. I think it's fairly common with our designs to have centered text above a form so maybe we should set text align left to overwrite that inheritance. I know this can be fixed by just not setting text align center on the parent but it's probably pretty easy for this to be overlooked and sent to prod

![image](https://user-images.githubusercontent.com/4015654/50710284-61104e80-101f-11e9-9788-725beac1f108.png)

**Comment by jstnjns** [comment]
seems reasonable

**Comment by stephenp** [comment]
Resolved
