### ISSUE TITLE
Input autofill styles

### ISSUE THREAD

**Issue by a-axton** [yankaindustries/mc-components#339]
Our inputs looks a little strange with autofill, from the new gifting page /gift/all-access-pass. For both dark/light styles
![image](https://user-images.githubusercontent.com/4015654/50994062-13d52680-14d0-11e9-9673-22c80fef1fc8.png)

**Comment by jstnjns** [comment]
wondering if the fix would be to disable autofill, or apply better styles.  the only problem with better styles is that we cannot style the container, just the input (meaning i think the only good looking style would be to change the color of the text, not sure if that's obvious enough)

**Comment by a-axton** [comment]
Are we moving away from the inline labels? Maybe this can wait until the new ones are done. Or disable the placeholder styles in the meantime

**Comment by jstnjns** [comment]
based on the designs we are seeing, that is most likely the case

**Comment by jstnjns** [comment]
inline labels are gone
