### ISSUE TITLE
Remove legacy tile tech debt

### ISSUE THREAD

**Issue by stephenp** [yankaindustries/mc-components#358]
```
/src/styles/base/mixins/_ratios.scss
```
The `> .background` and other classes in this file have been removed in our mc-components tile implementation, but we have legacy code in the mc main repo that need these styles.

I believe the logged in homepage is one of the biggest culprits, but it also lived on the category landing pages (which got rebuilt already).  Will need to check through the site more thoroughly to figure out where else this is used.

**Comment by bcfancher-mc** [comment]
@stephenp the ImageTile component uses both .background and .content classes.  Should this be refactored?  Specifically which are the classes we're wanting to deprecate? (there aren't that many classes in that file).

**Comment by jstnjns** [comment]
i can no longer find a reference to the ImageTile component in `masterclass`, i presume it was refactored to use Tile/TileImage.  going to remove
