### ISSUE TITLE
Icon in helper texts adjusts height of wrapper

### ISSUE THREAD

**Issue by stephenp** [yankaindustries/mc-components#372]
https://yankaindustries.github.io/mc-components/?selectedKind=Components%7CForms&selectedStory=Summary&full=0&addons=0&stories=1&panelRight=1&addonPanel=storybook%2Factions%2Factions-panel

the icon being added on error state is changing the height of the parent, which is making the text jump around:

https://cl.ly/3f06a32eaaba

We should probably investigate a fix for all mc-icons so that this isn't an issue (negative margin rem?)

**Comment by jstnjns** [comment]
Solved in #460
