### ISSUE TITLE
eslint --fix isn't formatting correctly

### ISSUE THREAD

**Issue by bernabe9** [yankaindustries/mc-components#38]
It's changing the JSX alignment.

Example:
1- change to a new branch: `git checkout -b test`
2- modify the first story of file `/src/components/Button/index.stories.js`, like this:
```javascript
<Button onClick={action('clicked')} primary>
  Button
</Button>
```
3- remove prettier-eslint to make sure that eslint --fix is causing the error:
```json
"lint-staged": {
    "src/**/*.js": [
      "prettier-eslint --write --log-level error", -> remove this line
      "eslint --fix",
      "git add"
    ],
    "src/**/*.scss": [
      "stylelint --fix",
      "git add"
    ]
  },
```
3- run git add
4- commit the changes: `git commit -m "test"`

Result:

```javascript
storiesOf('Button', module)
  .add(
    'primar',
    withInfo({ ...infoProps })(() => (
      <Button onClick={action('clicked')}
primary
      >
        Button
      </Button>
    )),
  )
```

**Comment by stephenp** [comment]
Moved to https://github.com/yankaindustries/mc-components/issues/44
