### ISSUE TITLE
Modal backdrop allows click through

### ISSUE THREAD

**Issue by fsarachu** [yankaindustries/mc-components#385]
# Problem
Because of the way `ClickOutside` handle events, it's possible to click a button that is behind the modal backdrop.
Currently, to prevent this, we found ourselves placing the following snippet on the `onClose` handler to work it around:
```javascript
  onModalClose = (source, event) => {
    event.preventDefault()
    event.stopPropagation()
    // ......
    // The actual handling code
  }
```

# Possible Solution
We could handle this on the actual `Modal` component, calling `event.preventDefault()` and `event.stopPropagation()` if the click source is `backdrop`

**Comment by bernabe9** [comment]
@fsarachu @jstnjns can we close this issue?
