### ISSUE TITLE
Spinner

### ISSUE THREAD

**Issue by bernabe9** [yankaindustries/mc-components#387]
Currently we don't have a spinner to show when the content is loading.

We should unify the button's spinner with a new content loading spinner.

**Comment by stephenp** [comment]
We now have a content spinner on button loading here:
https://yankaindustries.github.io/mc-components/?selectedKind=Components%7CButton&selectedStory=Summary&full=0&addons=0&stories=1&panelRight=1&addonPanel=storybook%2Factions%2Factions-panel

We also have a raw SVG here if you'd like to manipulate it:
https://github.com/yankaindustries/mc-components/blob/develop/src/assets/icons/loader.svg

The button loader component is here if you want to use it manually too:
https://github.com/yankaindustries/mc-components/blob/develop/src/components/ButtonLoader/index.js

Closing, but please reopen if this needs more discussion!

**Comment by jstnjns** [comment]
We need to abstract ButtonLoader to something that is not only meant for the Button.

**Comment by bcfancher-masterclass** [comment]
PR to add 'Loader':
https://github.com/yankaindustries/mc-components/pull/577
will replace current implementations of 'ButtonLoader' in a couple of experiments once this gets merged

**Comment by bcfancher-masterclass** [comment]
Loader has been created with intention to replace ButtonLoader altogether
