### ISSUE TITLE
Button overflows text content

### ISSUE THREAD

**Issue by bernabe9** [yankaindustries/mc-components#388]
Screenshot:
<img width="248" alt="screen shot 2019-03-08 at 11 49 20 am" src="https://user-images.githubusercontent.com/18464392/54035724-c3f5a180-4198-11e9-9f55-bc6eb1e3535a.png">

The issue is happening because we are setting a fixed height to the button (`height: 4em`)

**Comment by stephenp** [comment]
The height is set intentionally to vertically align child content like icons and text.  The issue here looks like the text is wrapping because the button is too small.

**Comment by bernabe9** [comment]
@stephenp are you saying that the button always will have the same height and we should guess the button's width to define the text content? 🤔 If we use flexbox we don't need to set a fixed height to vertical align child content

**Comment by stephenp** [comment]
@bernabe9 Correct, buttons should always be the same height. The thought process was if there's a button with an icon next to a button without an icon, they should both be the same height.

If we remove the manually set height value, the buttons can vary in height, which leads to inconsistencies when buttons of differing heights are next to each other.

**Comment by stephenp** [comment]
Please ping design about how they want this button to look at the breakpoint you're having issues at. They specifically do not allow multiline buttons per their design guidelines:

![image](https://user-images.githubusercontent.com/505670/54050316-b853ac00-4193-11e9-9f92-09944bbe0c44.png)
