### ISSUE TITLE
Add ability to select from Select dropdowns

### ISSUE THREAD

**Issue by stephenp** [yankaindustries/mc-components#440]
In `/src/components/SelectField/index.stories.js`

Programmatically choosing a `value` for a select doesn't seem to work.  

```
const membershipOptions = [
  {
    label: 'Silver',
    value: '1',
  },
  {
    label: 'Gold',
    value: '2',
  },
  {
    label: 'Platinum',
    value: '3',
  },
]

<Field
  component={SelectField}
  name='disabledChecked'
  disabled
  options={membershipOptions}
  value='Silver'
  label='
    This checkbox is disabled but has a selected option
  '
/>```

**Comment by jstnjns** [comment]
Fields don't use `value` prop, uses state to set values. See [story](http://localhost:9001/?selectedKind=Components%7CForms%2FSelect&selectedStory=SelectField&full=0&addons=1&stories=1&panelRight=1&addonPanel=mc%2Fprops%2Fpanel) for working example.
