### ISSUE TITLE
Retool show/hide animation handling

### ISSUE THREAD

**Issue by stephenp** [yankaindustries/mc-components#443]
Animations need a little reworking - seems like show/hide currently are tied into the accordion implementation so we should abstract this out to be reusable everywhere.  Then once completed, update documentation for `AnimationHandler`.

**Comment by jstnjns** [comment]
@stephenp did we do this already?

**Comment by bcfancher-masterclass** [comment]
ping @stephenp @jstnjns - has this been completed?

**Comment by jstnjns** [comment]
yea, we killed the ties to the `Accordion`.  now we just need to update the `AnimationHandler`, adding the `'show'` and `'hide'` options for the `type` prop

**Comment by bcfancher-masterclass** [comment]
actually it seems that's already been completed as well.  If no other items remaining this can probably be closed
