### ISSUE TITLE
automate release notes

### ISSUE THREAD

**Issue by jstnjns** [yankaindustries/mc-components#454]
maybe a bash script that grabs the commit messages until our last tag and somehow add that to the version commit message

**Comment by jstnjns** [comment]
https://stackoverflow.com/questions/12082981/get-all-git-commits-since-last-tag

**Comment by stephenp** [comment]
Using `git log --oneline` for a rollup, then grabbing each commit / pr's summary for formatting.  Doing this only on minor releases or higher.
