### ISSUE TITLE
Build grid component example

### ISSUE THREAD

**Issue by stephenp** [yankaindustries/mc-components#46]
Build out an example component showing our grid system similar to [bootstrap's documentation](https://getbootstrap.com/docs/4.0/layout/grid/).  The designers would like to see how it works in practice with their values before confirming final values.

**Comment by stephenp** [comment]
I'm not sure the best way to do this - build a custom component just for showing a grid layout seems like overkill and unnecessary - thoughts?

**Comment by bernabe9** [comment]
I think that it's an excellent idea to have an example of how to use the grid.

Maybe the best solution is to have another storybook for non-components styles. But for now, we can add it as you said using a custom component with a story to show the grid.

**Comment by jstnjns** [comment]
I know I'm a little late to the game, but per the convo at #16 I don't think we need a React component, but to just have the story include static HTML.

**Comment by stephenp** [comment]
Closing this issue since the component has been created, but we can continue this discussion in the following issue to flesh out the static markup section in mc-components:

https://github.com/yankaindustries/mc-components/issues/16
