### ISSUE TITLE
Icon builder should ignore hidden files

### ISSUE THREAD

**Issue by stephenp** [yankaindustries/mc-components#466]
Probably anything starting with a `.` here:
https://github.com/yankaindustries/mc-components/blob/develop/build/assets.js

When running `yarn build`, if you've opened the icon folder on a mac, a hidden file called `.DS_store` will be created.  The build script will then try to export this non-valid file as an image.

**Comment by jstnjns** [comment]
should be pretty easy to add a filter based on filename in that loop.  nice catch!
