### ISSUE TITLE
Remove gradient from VideoPlayer pause screens

### ISSUE THREAD

**Issue by stepchud** [yankaindustries/mc-components#468]
Many users have written to complain about not being able to see the screen when they pause the video. Some lessons have details on the screen they'd like to be able to review. As part of the auto-play experiment, we are adding a Show/Hide button to the pause screen. We want the gradient covering the video to go away when the user hides the pause screen. In order to accomplish this the plan was to remove the gradient from the VideoPlayer component and add it to the video players as a prop or something configurable.

**Comment by stepchud** [comment]
Here's a bunch of user feedback if you're curious what that looks like https://www.figma.com/file/YMe6RaHanCO79LXCMHOREi7c/Pause-Experience-Explorations

**Comment by stephenp** [comment]
So it looks like the pause screen style is baked into the video player component here:
https://github.com/yankaindustries/mc-components/blob/develop/src/styles/components/_video-player.scss#L33

If we'd like to remove it across all video player wherever they're used and design has signed off on this, we can make this change in mc-components.

**Comment by stephenp** [comment]
I believe this was resolved with https://github.com/yankaindustries/mc-components/pull/472

**Comment by stephenp** [comment]
Please reopen if this was not fixed in that release.
