### ISSUE TITLE
Responsive margin and padding helpers

### ISSUE THREAD

**Issue by stephenp** [yankaindustries/mc-components#474]
https://getbootstrap.com/docs/4.0/utilities/spacing/

**Comment by stephenp** [comment]
Open to discussion, but should we have responsive padding helpers, or trust in the responsive scaling helpers that were built with design's input?

**Comment by jstnjns** [comment]
scale

**Comment by jstnjns** [comment]
The number of LOC this would add would far outweigh the benefits.  We currently have 2 property helpers (padding + margin), controlled at 7 sides (l, t, r, b, x, y, *) at 13 sizes (12 + zero value), each having 3 values per media query via the scale (sm, md, lg).  546 rules for what we currently have...
