### ISSUE TITLE
Additional modifiers for 2-line and 3-line helpers

### ISSUE THREAD

**Issue by stephenp** [yankaindustries/mc-components#493]
![image](https://user-images.githubusercontent.com/505670/58212522-e7ae8b00-7ca3-11e9-9b08-d9fe30eddf2b.png)

We currently support 2-line and 3-line limits with our css helpers.  Would it make sense to add additional support for alignment within that 2-3 line helper if possible?

**Comment by jstnjns** [comment]
i don't think so.  we can use a combo of the new max line helpers and flexbox to achieve this
