### ISSUE TITLE
Configure Webpack

### ISSUE THREAD

**Issue by bernabe9** [yankaindustries/mc-components#5]
Configure Webpack for:
- Compile SCSS code
- Compile Javascript code
- Load images and other assets

**Comment by stephenp** [comment]
@a-axton and I were discussing this. If we're simply compiling / minifying the SCSS into a single file, is a single line with `node-sass` in the package.json file as a npm script sufficient?

**Comment by bernabe9** [comment]
Totally agree, we don't need Webpack to compile scss if we can do it with just one npm script
