### ISSUE TITLE
Modals v2

### ISSUE THREAD

**Issue by stephenp** [yankaindustries/mc-components#522]
Modals are now being used in new ways we didn't expect.  We need to improve our modals to support new and unexpected use cases.

## Overflowing content
While we initially built modals to showcase small chunks of content that would adapt to the height of the viewport, I believe we should handle some basic overflow logic to make sure modals don't appear broken if users don't implement overflow handling themselves.

I implemented a rough first pass at an idea here:
https://github.com/yankaindustries/masterclass/pull/10358/files#diff-19302661d09c3c963c78c250036ca67aR2

Things to think about:
- Responsive handling for viewport height doesn't account for url bar or bottom bar on mobile devices, so those need to be accounted for somehow
- Do we just need better documentation about how to handle overflowing?
- How can we keep vertical centering while preventing overflow outside of the viewport?

## Scrolling behavior when modal is toggled
When the modal is triggered, we add a `position: fixed;` to the body to prevent scrolling while the modal is active.  This unfortunately resets your scrollTop and you're brought to the top of the page, losing your place in the document.  This is particularly painful on the SEO pages where you might be in the middle of reading an article.

https://ourmasterclass.slack.com/archives/CGH3BN06M/p1564509297002500

We need to address this by preventing scroll while the modal is open *AND* making sure we return the user to their original position.  @jstnjns found [an article that might be of help](https://css-tricks.com/prevent-page-scrolling-when-a-modal-is-open/) when we implement this.

## Before launching v2
The modals need to support:
- [ ] Prevent scroll on activation
- [ ] Return user to scrolled position
- [ ] Handle overflowing content

**Comment by bcfancher-mc** [comment]
prevent Body scrolling and returning user to scrolled position were already fixed.  Handling overflow content is to be left as-is, for now.
