### ISSUE TITLE
Dropdown component - better responsive handling

### ISSUE THREAD

**Issue by stephenp** [yankaindustries/mc-components#524]
While it's an edge case, we should look into better resize handling of the dropdown component.  When breaking between the dropdown and fullscreen view, there's some weirdness in rendering.

Also causes some page overflow issues horizontally when you resize from a desktop resolution down to a smaller width.

![Kapture 2019-07-22 at 12 33 44](https://user-images.githubusercontent.com/505670/61659705-fe119c80-ac7c-11e9-941d-b602d81a5ac8.gif)

**Comment by bcfancher-mc** [comment]
so after investigating this, the width/height of the dropdown switches to 100vw/vh when resized less than 576 pixels; this is normal dropdown UX on mobile.  However it's still getting transformed unnecessarily, which is messing up the positioning:
transform: translate3d(69px, 294px, 0px);

I can't figure out where this transform is coming from, but this is pretty edge-case.

**Comment by bcfancher-mc** [comment]
including @jstnjns to look at this with me at a later time
