### ISSUE TITLE
Themes / dark / light

### ISSUE THREAD

**Issue by stephenp** [yankaindustries/mc-components#527]
We're having some discussions around nesting inverted selectors, and began thinking about the need to have a better way to support a "theme" on a per page basis.

As you can see here, simply changing the variables for dark and light do not work, since we use those variables across the board.  We'd need to adjust the use cases where those values are used to determine if they actually need to switch / look correct when switched, and use hard coded values here instead (for buttons, for example, the text should always be white, regardless of the theme, it should not use `$mc-color-light`.
![image](https://user-images.githubusercontent.com/505670/62235526-0a36e180-b382-11e9-93db-919dbe15d367.png)

In addition, we have to support `.mc-invert` nested inside of `.mc-invert` for the original use cases that were discussed here:

https://ourmasterclass.slack.com/archives/CB74RPL82/p1564593979004200

Then discussed further in the dev channel here:
https://ourmasterclass.slack.com/archives/CGH3BN06M/p1564595415018300

**Comment by bcfancher-masterclass** [comment]
starting a slack thread:
https://ourmasterclass.slack.com/archives/CGH3BN06M/p1570731121000100?thread_ts=1564601111.061600&cid=CGH3BN06M

**Comment by bcfancher-masterclass** [comment]
https://codepen.io/bcfancher/pen/XWWmZMp

**Comment by bcfancher-mc** [comment]
Now you can switch between light and dark themes using the respective classes:
.mc-theme-dark
.mc-theme-light (.mc-invert for compatibility, but deprecated)
