### ISSUE TITLE
Documentation for icon sizing

### ISSUE THREAD

**Issue by stephenp** [yankaindustries/mc-components#532]
We need to document the icon sizing helpers, where you can use `mc-icon--x` where x is a size 1-16 on the scale

```
.mc-icon {
  fill: currentColor;
  width: 16px;
  height: 16px;

  @for $i from 1 through 16 {
    &--#{$i} {
      @include step(font-size, $i);
    }
  }
```

**Comment by jstnjns** [comment]
i'm not entirely sure this is what we want to support for sizing. it's in there as a test, but should be considered incredibly beta.  thoughts on making it more official, or investigating a better route?

**Comment by stephenp** [comment]
I'm fine with it going live - seems to work well for any applications / use cases we've used it on

**Comment by stephenp** [comment]
Reopening to now document the icon sizing availability (now that the icons use the correct class)
