### ISSUE TITLE
ResposiveHandler => responsive(xs,sm,md,lg) function

### ISSUE THREAD

**Issue by juanlacruz** [yankaindustries/mc-components#558]
The `responsive` function is triggered multiple times, returning true at first if you check against mobile.

Let's say you are on desktop, and you do:
`responsive(1,2,3,4) === 1`

at first, it will return true, but then once the whole view is loaded it will return false

**Comment by bcfancher-masterclass** [comment]
Hello @juanlacruz,

Do you have a branch I can look at where this is happening?  I cannot reproduce this.

Thanks,
Brandon

**Comment by jstnjns** [comment]
@bcfancher-mc have this line console out what value it's returning and you'll see it fire twice the first time https://github.com/yankaindustries/mc-components/blob/develop/src/components/ResponsiveHandler/index.js#L78
