### ISSUE TITLE
VideoPlayer fill should be turned off when `fullscreen`

### ISSUE THREAD

**Issue by stephenp** [yankaindustries/mc-components#598]
Reported from a user on a 15" laptop screen:
https://ourmasterclass.slack.com/archives/C3R3UCT7G/p1571766491027000

The video player is being cut off on the left and right because of the class `vjs-fill-height`.  This was originally added to allow our components to have full bleed videos in the videoplayer without needing additional css.

The logic for checking which fill mode is needed lives here:
https://github.com/yankaindustries/mc-components/commit/8cab4c13fadcaa858299f7b777255940c65033e9

When refactoring for this bug, we should also change the fill mode class names to something specific to mc-components `mc-video-fill-height`? So our future selves don't go down a rabbit hole of looking through videojs documentation for their undocumented `fill-width` and `fill-height` features :P 

https://github.com/yankaindustries/mc-components/commit/8cab4c13fadcaa858299f7b777255940c65033e9#diff-2f33716a65e49723d1d1364fc58fe514R201

**Comment by bcfancher-mc** [comment]
@stephenp can you please clarify exact steps to reproduce?  Many thanks

**Comment by stephenp** [comment]
Steps to reproduce:

In Safari or Chrome (might be other browsers as well):
- Be on a 15" macbook pro resolution (inspector responsive modes might not work)
- Go to Aaron Franklin BBQ class page (lesson 3) while logged in with AAP: http://masterclass.com/classes/aaron-franklin-teaches-texas-style-bbq/chapters/smoke-pork-ribs
- Scrub to timestamp: 2:26
- Click on "fullscreen" button in bottom right hand corner of video player
- Observe video cutting off red "card" graphic (attached)

The issue (I believe) stems from the `vjs-fill-height` class which we add on the video player based in the logic here: https://github.com/yankaindustries/mc-components/commit/8cab4c13fadcaa858299f7b777255940c65033e9#diff-c00393e43603fb0a9c25af3001fe7719R399




![image](https://user-images.githubusercontent.com/505670/67327392-b513f300-f4cc-11e9-85f1-367ec55b9bf7.png)
