### ISSUE TITLE
new utility class "clickable", adds cursor pointer

### ISSUE THREAD

**Issue by a-axton** [yankaindustries/mc-components#621]
I've seen this requested a few times and just recently saw a dev create a selector just to add `cursor: pointer`

**Comment by stephenp** [comment]
I typically reply with feedback about adding an anchor class for any items that are clickable - you should be able to wrap whatever needs to be clicked with an `a` tag, but open to discussion on this since it sometimes means you're wrapping a LOT of content.

**Comment by jstnjns** [comment]
anchors have certain semantic value, i'm not sure it's always appropriate.  adding the class
