### ISSUE TITLE
VideoPlayer component prop validation

### ISSUE THREAD

**Issue by stephenp** [yankaindustries/mc-components#630]
https://github.com/yankaindustries/mc-components/blob/develop/src/components/VideoPlayer/index.js#L417

We currently pass `...restProps` to the VideoPlayer component so we can do things like pass video attributes (autoplay, muted, etc) to the video component.  The current implementation in `VideoPlayer` passes all props in, which can override our own set properties.

The implementation should be updated to append the properties instead of replace them.  Use case example: the videoplayer requires specific classes to be set: 

https://github.com/yankaindustries/mc-components/blob/develop/src/components/VideoPlayer/index.js#L433

If a user passes in their own classes, the `..restProps` will replace our required classNames, leading to the video player rendering incorrectly.

**Comment by jstnjns** [comment]
we should also pull out any additional props we expect to be sent to the component that are not valid HTML attributes:

```
hasAutoplay,
isLooped,
playerRef,
progress,
onPlayerReady,
onVideoReady,
onPlay,
onPause,
onEnd,
onTimeChange,
onFullscreenChange,
onError,
onSeek,
```

**Comment by jstnjns** [comment]
a lot of these have been removed (https://github.com/yankaindustries/mc-components/commit/03588ef7c2eef4fb7b48be42d9d586e19cab1f5a)
