### ISSUE TITLE
TileCaption pointer events bleeding through

### ISSUE THREAD

**Issue by stephenp** [yankaindustries/mc-components#637]
https://github.com/yankaindustries/mc-components/blob/develop/src/styles/components/_tile.scss#L176

`TileCaption` currently has an outside wrapper of `.mc-tile-caption` and an inner wrapper of `.mc-tile-caption__content`.  The outer wrapper has `pointer-events: none`;

Because the Tile layer is present at all times, if you have clickable items in a pause, end, or replay screen, those items are clickable when not visible.

The content layer should only be set to `pointer-events: auto` when it is visible (or it should only be rendered on the page when the state is true.

**Comment by jstnjns** [comment]
the issue was a use case specifically when hiding something improperly.  i don't think we should adjust the tile, but just not hide things using `{ opacity: 0; pointer-events: none; }`
