### ISSUE TITLE
VideoScreens should not be rendered (or displayed) when not in view

### ISSUE THREAD

**Issue by jstnjns** [yankaindustries/mc-components#641]
We currently set the opacity to 0 and turn off pointer events, but children can turn pointer events to auto and hijack clicks when invisible.

**Comment by stephenp** [comment]
Similar to https://github.com/yankaindustries/mc-components/issues/637

**Comment by jstnjns** [comment]
they will be rendered as to not disturb existing implementations, but set to `display: none`
