### ISSUE TITLE
Yarn Lint Fails After Switching to Master Branch

### ISSUE THREAD

**Issue by bcfancher-mc** [yankaindustries/mc-components#661]
No Puedo:
![image](https://user-images.githubusercontent.com/56046844/74892219-d8956000-533d-11ea-8eaf-e0e37cf7e916.png)

**Comment by bcfancher-mc** [comment]
Just curious why we need to have different cases? @jstnjns @stephenp ?

**Comment by jstnjns** [comment]
we shouldn't, all of the build scripts use capital `Icons` for their config.  please try renaming the directory locally with a capital `I` and see if that does not resolve the issue for you (as it did for me).  interestingly, the case is correct on github as well.  not sure what could cause this.  i tried to see if i could commit the case difference, but git does not recognize it as a change.

reopen this if changing the case does not resolve the issue
