### ISSUE TITLE
Carousel arrows cut off on mobile

### ISSUE THREAD

**Issue by stephenp** [yankaindustries/mc-components#688]
![image](https://user-images.githubusercontent.com/505670/78089372-198c8580-737c-11ea-8165-1ac93d96467a.png)

Need to work with design to address / refactor / rethink how arrows are handled for mobile resolutions since they need to live within the container.

For more context, this issue is due to the `overflow: hidden;` on the *carousel* scss, not the root `.container` style.  You can see this style here:

https://github.com/yankaindustries/mc-components/blob/master/src/styles/components/carousel/_base.scss#L24

**Comment by jstnjns** [comment]
you might be able to solve this by pulling the `mc-carousel__arrow-container` out of the  `mc-carousel__container`

**Comment by stephenp** [comment]
This was resolved with design by removing arrows on mobile
