### ISSUE TITLE
Integrate CircleCI or Travis

### ISSUE THREAD

**Issue by bernabe9** [yankaindustries/mc-components#7]

**Comment by jesseocon** [comment]
I would recommend going with CircleCI as we are already using CircleCI. Though we will need to start using version 2.0. That being said if there is a distinct feature set in Travis that we must have then let's discuss.

**Comment by bernabe9** [comment]
@jesseocon this project is already set up for CircleCI v2, we just need to enable it. Only an administrator can enable CircleCI. @a-axton can you enable it?

**Comment by stephenp** [comment]
Looks like when I go to circleCI, I have to input my payment information even for the free plan.  @jesseocon can you link up the CircleCI integration for our mc-components repo?

**Comment by stephenp** [comment]
Resolved, circleCI has been added
