### ISSUE TITLE
The Scale section in the storybook seems to have a hardcoded `rem` in each scale

### ISSUE THREAD

**Issue by missx** [yankaindustries/mc-components#728]
## Screenshots

![image](https://user-images.githubusercontent.com/2998072/84188916-c2391e80-aa6a-11ea-8b42-9b7c35e5ad49.png)

![image](https://user-images.githubusercontent.com/2998072/84188938-cb29f000-aa6a-11ea-99ed-397c09ecb42b.png)

![image](https://user-images.githubusercontent.com/2998072/84188957-d250fe00-aa6a-11ea-8400-2f830f3b7b82.png)

**Comment by stephenp** [comment]
Fixed!
