### ISSUE TITLE
automate release process

### ISSUE THREAD

**Issue by jstnjns** [yankaindustries/mc-components#739]
we can trigger some automations when we create a release
https://help.github.com/en/actions/reference/events-that-trigger-workflows#release-event-release

we can automatically publish to NPM
https://help.github.com/en/actions/language-and-framework-guides/publishing-nodejs-packages#publishing-packages-to-the-npm-registry

we can also automatically push messaging
https://github.com/marketplace/actions/github-action-for-slack

**Comment by stephenp** [comment]
Ez - it's part of the monorepo now, so woo, we did it!
